# Generated by Django 3.2.12 on 2022-09-26 18:45

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('location', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnailpic', models.ImageField(upload_to=api.models.PortfolioEntry.rename_pic)),
                ('title', models.CharField(default='title', max_length=255)),
                ('blurb', models.CharField(default='blurb', max_length=255)),
                ('video', models.FileField(blank=True, default='', upload_to=api.models.PortfolioEntry.rename_vid)),
                ('description', models.TextField(default='description')),
                ('date_created', models.DateField()),
                ('github_link', models.CharField(blank=True, default='', max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioEntryPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_pos', models.IntegerField()),
                ('pic', models.ImageField(upload_to=api.models.PortfolioEntryPictures.rename_pic)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.portfolioentry')),
            ],
        ),
    ]
