# Generated by Django 3.2.12 on 2022-05-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('fname', models.CharField(default='Tomas', max_length=255)),
                ('lname', models.CharField(default='Premoli', max_length=255)),
                ('aboutme', models.TextField(default='')),
                ('cv', models.FileField(upload_to='pdf')),
                ('github_link', models.CharField(default='https://github.com/tpremoli', max_length=255)),
                ('linkedin_link', models.CharField(default='https://www.linkedin.com/in/tomas-premoli-008016144/', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnailpic', models.ImageField(upload_to='')),
                ('title', models.CharField(default='title', max_length=255)),
                ('blurb', models.TextField(default='blurb')),
                ('technologies_used', models.CharField(default='Javascript, HTML', max_length=255)),
                ('date_created', models.DateField()),
                ('github_link', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioEntryPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.portfolioentry')),
            ],
        ),
    ]
