# Generated by Django 4.1.4 on 2022-12-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb', models.TextField(blank=True, default='')),
                ('skills', models.TextField(blank=True, default='')),
                ('classes', models.TextField(blank=True, default='')),
                ('pic', models.ImageField(upload_to='api/media/me')),
            ],
        ),
    ]
