# Generated by Django 3.2.12 on 2022-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='cv',
            field=models.FileField(upload_to='api/pdf'),
        ),
    ]
