# Generated by Django 4.1.4 on 2023-01-02 20:10

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tutoringdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='bannerpic',
            field=models.ImageField(upload_to=api.models.MyData.rename_bannerpic),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='cv',
            field=models.FileField(upload_to=api.models.MyData.rename_pdf, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='pic',
            field=models.ImageField(upload_to=api.models.MyData.rename_pic),
        ),
    ]
