# Generated by Django 3.2.12 on 2022-05-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mydata_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='cv',
            field=models.FileField(upload_to='api/media/me\\cv.pdf'),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='pic',
            field=models.ImageField(upload_to='api/media/me\\pic.png'),
        ),
    ]
