# Generated by Django 4.1.4 on 2023-01-02 20:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mydata_bannerpic_alter_mydata_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringdata',
            name='pic',
            field=models.ImageField(upload_to=api.models.TutoringData.rename_pic),
        ),
    ]
