# Generated by Django 4.1.4 on 2023-05-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tutoringdata_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
