# Generated by Django 3.2.12 on 2022-05-03 16:46

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220503_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='cv',
            field=models.FileField(upload_to=api.models.MyData.rename_pdf, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='pic',
            field=models.ImageField(upload_to=api.models.MyData.rename_pic),
        ),
    ]
