# Generated by Django 4.2.4 on 2023-12-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
