# Generated by Django 3.2.12 on 2022-05-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220503_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydata',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='mydata',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='mydata',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='mydata',
            name='pic',
        ),
    ]
