# Generated by Django 4.2.4 on 2023-12-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pdf_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
