# Generated by Django 3.2.12 on 2022-05-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220506_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='lname',
            field=models.CharField(default='Premoli', max_length=255),
        ),
    ]
