# Generated by Django 4.2.4 on 2023-12-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pdf_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='readpdf_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
