# Generated by Django 3.2.12 on 2022-05-06 22:12

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_mydata_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='cv',
            field=models.FileField(default='', upload_to=api.models.MyData.rename_pdf, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mydata',
            name='pic',
            field=models.ImageField(default='', upload_to=api.models.MyData.rename_pic),
            preserve_default=False,
        ),
    ]
