# Generated by Django 4.2.4 on 2023-12-09 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pdf_readpdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.pdf'),
        ),
    ]
