# Generated by Django 4.2.4 on 2023-12-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_portfolioentry_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='readpdf_url',
        ),
    ]
