# Generated by Django 3.2.12 on 2022-05-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_contactentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactentry',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
