# Generated by Django 3.2.12 on 2022-05-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220520_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
