# Generated by Django 3.2.12 on 2022-06-09 23:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220520_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentry',
            name='thumbnailpic',
            field=models.ImageField(upload_to=api.models.PortfolioEntry.rename_pic),
        ),
    ]
