# Generated by Django 3.2.12 on 2022-06-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_portfolioentry_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='video',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='blurb',
            field=models.CharField(default='blurb', max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='technologies_used',
            field=models.TextField(default=''),
        ),
    ]
