# Generated by Django 3.2.12 on 2022-06-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220612_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentry',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
