# Generated by Django 3.2.12 on 2022-06-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_portfolioentry_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentry',
            name='github_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='video',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
