# Generated by Django 3.2.12 on 2022-08-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_portfolioentry_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioentry',
            name='technologies_used',
        ),
    ]
