# Generated by Django 3.2.12 on 2022-08-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_portfolioentry_technologies_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentrypictures',
            name='pic_pos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
