# Generated by Django 3.2.12 on 2022-08-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_portfolioentrypictures_pic_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentrypictures',
            name='pic_pos',
            field=models.IntegerField(unique=True),
        ),
    ]
