# Generated by Django 3.2.12 on 2022-08-07 15:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_portfolioentrypictures_pic_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentrypictures',
            name='pic',
            field=models.ImageField(upload_to=api.models.PortfolioEntryPictures.rename_pic),
        ),
    ]
