# Generated by Django 3.2.12 on 2022-08-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_portfolioentrypictures_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentrypictures',
            name='pic_pos',
            field=models.IntegerField(),
        ),
    ]
