# Generated by Django 3.2.12 on 2022-09-14 18:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_portfolioentrypictures_pic_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='bannerpic',
            field=models.ImageField(default='', upload_to=api.models.MyData.rename_pic),
            preserve_default=False,
        ),
    ]
