# Generated by Django 3.2.12 on 2022-09-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_mydata_bannerpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
