# Generated by Django 3.2.12 on 2022-09-14 19:03

import api.models
import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20220914_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='bannerpic',
            field=models.ImageField(storage=api.storage.OverwriteStorage(), upload_to=api.models.MyData.rename_pic),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='pic',
            field=models.ImageField(storage=api.storage.OverwriteStorage(), upload_to=api.models.MyData.rename_pic),
        ),
    ]
