# Generated by Django 3.2.12 on 2022-09-14 19:13

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20220914_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='bannerpic',
            field=models.ImageField(storage=api.storage.OverwriteStorage(), upload_to='api/media/me/banner.jpg'),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='pic',
            field=models.ImageField(storage=api.storage.OverwriteStorage(), upload_to='api/media/me/me.jpg'),
        ),
    ]
