# Generated by Django 3.2.12 on 2022-09-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20220914_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='bannerpic',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
