# Generated by Django 3.2.12 on 2022-09-14 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20220914_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='cv',
            field=models.FileField(upload_to='api/media/me/cv.pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
